In [1]:
import os
from pathlib import Path
if Path.cwd().name != 'DaSPi':
    os.chdir('..')
assert str(Path.cwd()).endswith('DaSPi'), f'Please run this notebook from the root of the DaSPi repository {Path.cwd()}'

import daspi
import pandas as pd
daspi.STR.LANGUAGE = 'de'

In [2]:
source = pd.DataFrame({
    'A': [1, 0, 1, 1, 0, 1],
    'B': [-1, 1, 0, -1, 1, 0],
    'C': [3.1, 6.1, 9.1, 12.0, 15.0, 18.1],
    'Target': [11, 19, 30, 42, 49, 50]})
target = 'Target'
categorical = ['A', 'B', 'C']
continuous = []
alpha = 0.05
lm = daspi.LinearModel(source, target, categorical, continuous, alpha, order=2)
gofs = list(lm.recursive_feature_elimination())
lm

c:\Users\ch0rjg\Festo\FMT-Product Care Versuch - Documents\Datenwissenschaft\Bibliotheken\DaSPi\daspi\anova\utils.py:218: UserWarning: ANOVA table could not be calculated because the model is underdetermined.
  warnings.warn(
c:\Users\ch0rjg\Festo\FMT-Product Care Versuch - Documents\Datenwissenschaft\Bibliotheken\DaSPi\daspi\anova\utils.py:218: UserWarning: ANOVA table could not be calculated because the model is underdetermined.
  warnings.warn(
c:\Users\ch0rjg\Festo\FMT-Product Care Versuch - Documents\Datenwissenschaft\Bibliotheken\DaSPi\daspi\anova\utils.py:218: UserWarning: ANOVA table could not be calculated because the model is underdetermined.
  warnings.warn(
c:\Appl\Python\.virtualenvs\DataScience-DY0ovQ8g-3.11\Lib\site-packages\statsmodels\regression\linear_model.py:1796: RuntimeWarning: divide by zero encountered in divide
  return 1 - (np.divide(self.nobs - self.k_constant, self.df_resid)
c:\Appl\Python\.virtualenvs\DataScience-DY0ovQ8g-3.11\Lib\site-packages\statsmodels\regression\linear_model.py:1796: RuntimeWarning: invalid value encountered in scalar multiply
  return 1 - (np.divide(self.nobs - self.k_constant, self.df_resid)

Formel:
Target ~ 3.1068*C

Zusammenfassung der Anpassungsgüte:
   hierarchical least_term   p_least        s        aic        r2    r2_adj  \
0          True          C  0.000003  3.78755  33.913966  0.991086  0.989304

    r2_pred
0  0.881378

Parameterstatistik:
       coef   std err          t         p    ci_low    ci_upp
C  3.106845  0.131767  23.578402  0.000003  2.768129  3.445562

Varianzanalyse:
Typ-II    DF           SS           MS           F         p        n2
Source
C          1  7975.272318  7975.272318  555.941032  0.000003  0.991086
Residual   5    71.727682    14.345536         NaN       NaN  0.008914

In [3]:
print(repr(lm))

Formel:
Target ~ 3.1068*C

Zusammenfassung der Anpassungsgüte:
   hierarchical least_term   p_least        s        aic        r2    r2_adj  \
0          True          C  0.000003  3.78755  33.913966  0.991086  0.989304

    r2_pred
0  0.881378

Parameterstatistik:
       coef   std err          t         p    ci_low    ci_upp
C  3.106845  0.131767  23.578402  0.000003  2.768129  3.445562

Varianzanalyse:
Typ-II    DF           SS           MS           F         p        n2
Source
C          1  7975.272318  7975.272318  555.941032  0.000003  0.991086
Residual   5    71.727682    14.345536         NaN       NaN  0.008914

In [4]:
lm = daspi.LinearModel(source, target, categorical, continuous, alpha, order=2).fit()
lm

c:\Appl\Python\.virtualenvs\DataScience-DY0ovQ8g-3.11\Lib\site-packages\statsmodels\regression\linear_model.py:1718: RuntimeWarning: divide by zero encountered in scalar divide
  return np.dot(wresid, wresid) / self.df_resid
c:\Users\ch0rjg\Festo\FMT-Product Care Versuch - Documents\Datenwissenschaft\Bibliotheken\DaSPi\daspi\anova\utils.py:218: UserWarning: ANOVA table could not be calculated because the model is underdetermined.
  warnings.warn(
c:\Users\ch0rjg\Festo\FMT-Product Care Versuch - Documents\Datenwissenschaft\Bibliotheken\DaSPi\daspi\anova\utils.py:218: UserWarning: ANOVA table could not be calculated because the model is underdetermined.
  warnings.warn(
c:\Appl\Python\.virtualenvs\DataScience-DY0ovQ8g-3.11\Lib\site-packages\statsmodels\regression\linear_model.py:1796: RuntimeWarning: divide by zero encountered in divide
  return 1 - (np.divide(self.nobs - self.k_constant, self.df_resid)
c:\Appl\Python\.virtualenvs\DataScience-DY0ovQ8g-3.11\Lib\site-packages\statsmodels\regression\linear_model.py:1796: RuntimeWarning: invalid value encountered in scalar multiply
  return 1 - (np.divide(self.nobs - self.k_constant, self.df_resid)
c:\Users\ch0rjg\Festo\FMT-Product Care Versuch - Documents\Datenwissenschaft\Bibliotheken\DaSPi\daspi\anova\utils.py:218: UserWarning: ANOVA table could not be calculated because the model is underdetermined.
  warnings.warn(
c:\Appl\Python\.virtualenvs\DataScience-DY0ovQ8g-3.11\Lib\site-packages\statsmodels\regression\linear_model.py:1783: RuntimeWarning: divide by zero encountered in scalar divide
  return 1 - self.ssr/self.centered_tss
c:\Users\ch0rjg\Festo\FMT-Product Care Versuch - Documents\Datenwissenschaft\Bibliotheken\DaSPi\daspi\anova\utils.py:152: RuntimeWarning: divide by zero encountered in scalar divide
  _vif[name] = (1 / (1 - r2))

Formel:
Target ~ -0.7303 + 10.5081*A - 0.8315*B + 10.4070*A:B + 4.6317*C - 2.4095*A:C - 1.2609*B:C

Zusammenfassung der Anpassungsgüte:
   hierarchical least_term  p_least   s         aic   r2  r2_adj  r2_pred
0          True  Intercept      NaN NaN -345.038544  1.0     NaN      1.0

Parameterstatistik:
                coef  std err    t   p  ci_low  ci_upp
Intercept  -0.730337      inf -0.0 NaN     NaN     NaN
A          10.508115      inf  0.0 NaN     NaN     NaN
B          -0.831461      inf -0.0 NaN     NaN     NaN
A:B        10.406991      inf  0.0 NaN     NaN     NaN
C           4.631710      inf  0.0 NaN     NaN     NaN
A:C        -2.409488      inf -0.0 NaN     NaN     NaN
B:C        -1.260924      inf -0.0 NaN     NaN     NaN

Varianzanalyse:
                 VIF
Intercept   0.000000
A                inf
B                inf
A:B              inf
C          11.753205
A:C        39.676638
B:C        20.466696

In [5]:
import numpy as np
import pandas as pd

dm = pd.DataFrame({
        'Intercept': [1, 1, 1, 1, 1, 1],
        'A': [-1, 1, 1, -1, -1, 1],
        'B': [0, -1, 0, -1, 1, 1],
        'AB': [0, -1, 0, 1, -1, 1],
        'Center': [1, 0, 1, 0, 0, 0]})

X = dm.values
# P = X(X'X)^(-1)X'
P = np.dot(X, np.dot(np.linalg.inv(np.dot(X.T, X)), X.T))
p_diag = np.diag(P)
p_diag

array([0.66666667, 0.91666667, 0.66666667, 0.91666667, 0.91666667,
       0.91666667])

In [6]:
dm = pd.DataFrame({
        'Ergebnis': [7.5292, 11.1151, 8.3440, 11.9081, 10.9183, 11.7622],
        'A': [-1, 1, 1, -1, -1, 1],
        'B': [0, -1, 0, -1, 1, 1],
        'Center': [1, 0, 1, 0, 0, 0]})
lm = daspi.LinearModel(dm, 'Ergebnis', ['A', 'B'], ['Center'], order=2).fit()
lm.r2_pred() - 0.350426519634100657

1.8318679906315083e-14